import { useState } from "react";
import { generateOutput } from "./source.js";
import { getPokemonFromList } from "./source.js";
import { getPokemonFromImportable, getPokemonFromImportables, exportList, Pokemon } from "./source.js";
import { convertBBCodeToList } from "./source.js";

export default function TextEntryBox({ list, setList, options }) {
  const [text, setText] = useState("");
  const [output, setOutput] = useState("");
  const [exportFormat, setExportFormat] = useState("bbcode");
  const speedStageConversionTable = {
    0.5: "-2",
    0.67: "-1",
    1: 0,
    1.5: "+1",
    2: "+2",
    //have to add the values again in reverse
    "-2": 0.5,
    "-1": 0.67,
    0: 1,
    "+1": 1.5,
    "+2": 2,
  };

  async function addClick() {
    var pokemon;
    if (options.mode === "set") {
      // support multiple importables separated by one or more blank lines
      const pokemons = await getPokemonFromImportables(text, options);
      if (pokemons != null && pokemons.length > 0) {
        setList((list) => [...list, ...pokemons]);
      } else {
        alert(
          "Invalid input. Input should be one or more Pokemon Showdown importable sets separated by a blank line."
        );
      }
    } else {
      pokemon = await getPokemonFromList(text, options);
      if (pokemon != null) {
        setList(list.concat(pokemon));
      } else {
        alert(
          "Invalid input. Input should be a list of Pokemon seperated by commas (ex. Abra,Porygon,Cacnea)"
        );
      }
    }
  }
  async function generateClick() {
    //generate output in selected format
    setOutput(await exportList(list, exportFormat, speedStageConversionTable));
  }

  function clearList() {
    if (window.confirm("Are you sure you want to clear the list?")) {
      setList([]);
    }
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(output);
  }

  async function importList() {
    if (
      window.confirm(
        "WARNING: Only speed tier lists output by this website can be imported. Importing tier lists not generated by this website may have unexpected results."
      )
    ) {
      // try JSON
      try {
        const parsed = JSON.parse(text);
        if (Array.isArray(parsed)) {
          const toAdd = [];
          for (const item of parsed) {
            const name = item.name || item.Name || item.NAME;
            if (!name) continue;
            const iv = item.iv ?? item.IV ?? options.iv;
            const ev = item.ev ?? item.EV ?? options.ev;
            const level = item.level ?? options.level;
            const natureRaw = item.nature ?? item.Nature ?? "Neutral";
            const nature =
              natureRaw === "Positive" || natureRaw === "positive" ? 1.1 : natureRaw === "Negative" || natureRaw === "negative" ? 0.9 : 1;
            const speedStageRaw = item.speedStage ?? item.SpeedStage ?? item.boost ?? item.speed_stage ?? item["speedStage"];
            const reverseTable = {
              "-2": 0.5,
              "-1": 0.67,
              0: 1,
              "+1": 1.5,
              "+2": 2,
            };
            const speedStage = reverseTable[speedStageRaw] ?? parseFloat(speedStageRaw) ?? options.speedStage;
            const p = new Pokemon(name, item.baseSpeed ?? 0, iv, ev, level, nature, 0, speedStage);
            if (!p.baseSpeed) await p.getBaseSpeed();
            p.calculateSpeed();
            toAdd.push(p);
          }
          if (toAdd.length > 0) {
            setList(list.concat(toAdd));
            return;
          }
        }
      } catch (e) {
        // not JSON
      }

      // try CSV
      try {
        function parseCSV(input) {
          const lines = input.split(/\r?\n/).filter((l) => l.trim() !== "");
          if (lines.length === 0) return [];
          const parseLine = (line) => {
            const res = [];
            let cur = "";
            let inQuotes = false;
            for (let i = 0; i < line.length; i++) {
              const ch = line[i];
              if (inQuotes) {
                if (ch === '"') {
                  if (line[i + 1] === '"') {
                    cur += '"';
                    i++;
                  } else {
                    inQuotes = false;
                  }
                } else {
                  cur += ch;
                }
              } else {
                if (ch === ',') {
                  res.push(cur);
                  cur = "";
                } else if (ch === '"') {
                  inQuotes = true;
                } else {
                  cur += ch;
                }
              }
            }
            res.push(cur);
            return res;
          };
          const headers = parseLine(lines[0]);
          const out = [];
          for (let i = 1; i < lines.length; i++) {
            const vals = parseLine(lines[i]);
            const obj = {};
            for (let j = 0; j < headers.length; j++) {
              obj[headers[j].trim()] = vals[j] !== undefined ? vals[j].trim() : "";
            }
            out.push(obj);
          }
          return out;
        }

        const rows = parseCSV(text);
        if (rows.length > 0) {
          const toAdd = [];
          for (const row of rows) {
            const name = row.name || row.Name || row.NAME || row.name?.replace?.(/"/g, "") ;
            if (!name) continue;
            const iv = row.iv ?? row.IV ?? options.iv;
            const ev = row.ev ?? row.EV ?? options.ev;
            const level = row.level ?? options.level;
            const natureRaw = row.nature ?? "Neutral";
            const nature = natureRaw === "Positive" ? 1.1 : natureRaw === "Negative" ? 0.9 : 1;
            const reverseTable = {
              "-2": 0.5,
              "-1": 0.67,
              0: 1,
              "+1": 1.5,
              "+2": 2,
            };
            const speedStage = reverseTable[row.speedStage] ?? parseFloat(row.speedStage) ?? options.speedStage;
            const p = new Pokemon(name, row.baseSpeed ?? 0, iv, ev, level, nature, 0, speedStage);
            if (!p.baseSpeed) await p.getBaseSpeed();
            p.calculateSpeed();
            toAdd.push(p);
          }
          if (toAdd.length > 0) {
            setList(list.concat(toAdd));
            return;
          }
        }
      } catch (e) {
        // not CSV
      }

      // fallback: try existing BBCode import
      var pokemon = await convertBBCodeToList(text, speedStageConversionTable);
      if (pokemon != null) {
        setList(list.concat(pokemon));
      } else {
        alert("Error occured importing list.");
      }
    }
  }

  return (
    <>
      <div>
        <textarea
          id="textInput"
          name="textInput"
          rows="10"
          cols="50"
          placeholder="Enter your set or list of Pokemon here..."
          onChange={(e) => setText(e.target.value)}
        ></textarea>
        <br />
        <button onClick={addClick}>Add to list</button>
        <div className="divider" />
        <button onClick={importList}>Import existing list</button>
        <div className="divider" />
        <button onClick={clearList}>Clear list</button>
      </div>

      <div>
        <label htmlFor="exportFormat">Export format: </label>
        <select id="exportFormat" onChange={(e) => setExportFormat(e.target.value)} value={exportFormat}>
          <option value="bbcode">BBCode (legacy)</option>
          <option value="json">JSON</option>
          <option value="csv">CSV</option>
        </select>
        <br />
        <textarea
          id="textOutput"
          name="textOutput"
          rows="10"
          cols="50"
          placeholder="Output will appear here..."
          value={output}
          readOnly
        ></textarea>
        <br />
        <button onClick={generateClick}>
          Generate speed tier list from added Pokemon
        </button>
        <div className="divider" />
        <button onClick={copyToClipboard}>Copy output to clipboard</button>
      </div>
    </>
  );
}
